// src/routes/Hero.svelte
<script>
</script>

<div class="ml-4 mt-3">
	<p class="font-bold text-2xl ml-4 text-white">
		Hi, my name is nesbeer, <br />
		i'm a <span class="underline">developer,</span> video editor <br />
		and youtuber
	</p>
	<div class="mt-3 underline">
		<a class="ml-4 font-bold mt-4 text-xl text-white" href="mailto:itznesbro@proton.me">contact</a>
		<br />
		<a href="https://youtube.com/@ItzNesbro" class="ml-4 font-bold mt-4 text-base text-gray-400"
			>youtube</a
		>
		<br />
		<a href="https://dsc.gg/itznesbro" class="ml-4 font-bold mt-4 text-sm text-gray-400">discord</a>
	</div>
</div>

// src/components/Hero.tsx
import Link from "next/link";
import React from "react";

const Hero: React.FC = () => {
  return (
    <div className="container p-2">
      <div className="mb-2">
        <h2 className="text-2xl font-medium">
          Hi, my name is nesbeer,
          <br /> i'm a <span className="text-primary underline">developer</span>
          , video editor, <br /> and youtuber
        </h2>
      </div>
      <div className="font-medium underline">
        <h2 className="text-2xl">
          <a href="mailto:itznesbro@proton.me">contact</a>
        </h2>
        <h3 className="text-xl text-accent">
          <Link href="https://dsc.gg/itznesbro" target="_blank">
            discord
          </Link>
        </h3>
        <h4 className="text-lg text-primary">
          <Link href="https://github.com/ItzNesbroDev" target="_blank">
            github
          </Link>
        </h4>
      </div>
    </div>
  );
};

export default Hero;
